MODEL_PARAMETERS:
  FRAME_EMBEDDING_SIZE: 64
  FRAME_PROJECTION_SIZE: 43
  N_PHONEMES: 43
  N_TOKENS: 43
  FIXED_NEURAL_SEQUENCE_LENGTH: 1600
  N_TEMPORAL_ENCODER_STATE: 64
  N_TEMPORAL_ENCODER_HEAD: 4
  N_TEMPORAL_ENCODER_LAYER: 4
  max_token_sequence_length: 100
  N_DECODER_STATE: 64
  N_DECODER_HEAD: 4
  N_DECODER_LAYER: 1
  PRECISION: float32